In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Churn_Modelling.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
# drop unnecessary cols
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [6]:
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [7]:
one_hot_encoder = OneHotEncoder(handle_unknown='ignore')
geo_encoded = one_hot_encoder.fit_transform(df[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=one_hot_encoder.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [8]:
# combine onehot encoded cols
df = pd.concat([df.drop('Geography', axis=1), geo_encoded_df], axis=1)
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [9]:
# target Split
X = df.drop('EstimatedSalary', axis=1)
y = df['EstimatedSalary']

In [10]:
# train test Split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
import pickle

with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(one_hot_encoder, file)

with open ('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

ANN Model

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
opt = tf.keras.optimizers.Adam(learning_rate=0.01)
loss = tf.keras.losses.MeanAbsoluteError()

In [14]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

## compile the model
model.compile(optimizer=opt,loss=loss,metrics=['mae'])

model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

d:\ANN-Classification\ann-env\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Setup tensor board
log_dir = 'regression_logs/fit/' + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

# Setup EarlyStopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)

In [16]:
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs = 100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - loss: 79888.0859 - mae: 79888.0859 - val_loss: 51514.4688 - val_mae: 51514.4688
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 50309.6875 - mae: 50309.6875 - val_loss: 50538.1523 - val_mae: 50538.1523
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49907.6250 - mae: 49907.6250 - val_loss: 50447.2305 - val_mae: 50447.2305
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49716.0000 - mae: 49716.0000 - val_loss: 50382.9102 - val_mae: 50382.9102
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49624.6797 - mae: 49624.6797 - val_loss: 50336.8945 - val_mae: 50336.8945
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49506.3047 - mae: 49506.3047 - val_loss: 50274.5000 - val_mae: 50274.5000
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49524.1055 - mae: 49524.1055 - val_loss: 50329.1797 - val_mae: 50329.1797
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49439.3555 - mae: 49439.3555 - val_loss: 50375.3359 - val_mae: 50375.3359
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 49423.3477 - mae: 49423.3477 - val_loss: 50601.0391 - val_mae: 50601.0391
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 49369.1680 - mae: 49369.1680 - val_loss: 50467.3242 - val_mae: 50467.3242
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49375.1836 - mae: 49375.1836 - val_loss: 50383.0742 - val_mae: 50383.0742
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49370.0039 - mae: 49370.0039 - val_loss: 50505.5898 - val_mae: 50505.5898
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 49315.1172 - mae: 49315.1172 - val_loss: 50579.2695 - val_mae: 50579.2695
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49333.1758 - mae: 49333.1758 - val_loss: 50619.5156 - val_mae: 50619.5156
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 49324.9609 - mae: 49324.9609 - val_loss: 50355.6953 - val_mae: 50355.6953
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49287.0664 - mae: 49287.0664 - val_loss: 50643.6953 - val_mae: 50643.6953
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 49287.7969 - mae: 49287.7969 - val_loss: 50472.8008 - val_mae: 50472.8008
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 49262.8594 - mae: 49262.8594 - val_loss: 50481.6914 - val_mae: 50481.6914
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49240.7383 - mae: 49240.7383 - val_loss: 50557.3516 - val_mae: 50557.3516
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49226.3828 - mae: 49226.3828 - val_loss: 50560.1719 - val_mae: 50560.1719
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 49215.4023 - mae: 49215.4023 - val_loss: 50473.9492 - val_mae: 50473.9492

In [17]:
%load_ext tensorboard

In [18]:
%tensorboard --logdir regression_logs/fit

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "d:\ANN-Classification\ann-env\Scripts\tensorboard.exe\__main__.py", line 2, in <module>
  File "D:\ANN-Classification\ann-env\Lib\site-packages\tensorboard\main.py", line 27, in <module>
    from tensorboard import default
  File "D:\ANN-Classification\ann-env\Lib\site-packages\tensorboard\default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

In [19]:
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Test MAE: {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 50274.5000 - mae: 50274.5000
Test MAE: 50274.5

In [20]:
model.save('regression_model.keras')